#!/usr/bin/env python3
"""Build the playable Punjabi word bank from open-source sources only.

Sources
-------
* Punjabi Wikipedia article titles
  https://dumps.wikimedia.org/pawiki/ — CC BY-SA 4.0
* Punjabi Wiktionary article titles
  https://dumps.wikimedia.org/pawiktionary/ — CC BY-SA 4.0
* LibreOffice Punjabi Hunspell dictionary (pa_IN.dic)
  https://github.com/LibreOffice/dictionaries — MPL-2.0

This script never downloads copyrighted dictionaries. Re-run it after
placing source files in data/raw/.
"""

from __future__ import annotations

import gzip
import json
import os
import re
import unicodedata
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW = os.path.join(ROOT, "data", "raw")
OUT_JS = os.path.join(ROOT, "data", "words.js")
OUT_META = os.path.join(ROOT, "data", "wordlist-meta.json")

# Gurmukhi letters and signs, excluding digits (U+0A66–U+0A6F).
GURMUKHI = re.compile(r"^[\u0A01-\u0A65\u0A70-\u0A75]+$")
HAS_BASE = re.compile(r"[\u0A05-\u0A39\u0A59-\u0A5E\u0A72-\u0A73]")
MIN_LEN = 2
MAX_LEN = 6

INDEPENDENT = set("ਅਆਇਈਉਊਏਐਓਔੲੳ")
CONSONANTS = set("ਕਖਗਘਙਚਛਜਝਞਟਠਡਢਣਤਥਦਧਨਪਫਬਭਮਯਰਲਲ਼ਵਸ਼ਸਹੜਖ਼ਗ਼ਜ਼ਫ਼")
MATRAS = set("ਾਿੀੁੂੇੈੋੌ")
SIGNS = set("ਂਃੰੱੑੵ")
NUKTA = "਼"
VIRAMA = "੍"


def akshars(word: str) -> list[str]:
    """Split a Gurmukhi word into akshar units (letter + matra/signs)."""
    clusters: list[str] = []
    for ch in word:
        if not clusters:
            clusters.append(ch)
            continue
        last = clusters[-1]
        if ch in MATRAS or ch in SIGNS or ch == NUKTA or ch == VIRAMA:
            clusters[-1] = last + ch
            continue
        if ch in CONSONANTS and last.endswith(VIRAMA):
            clusters[-1] = last + ch
            continue
        clusters.append(ch)
    return clusters


def tokens_from_title(title: str) -> list[str]:
    title = title.replace("_", " ")
    parts = re.split(r"[\s\-\u2013\u2014/,()\[\]|:]+", title)
    out: list[str] = []
    for part in parts:
        word = unicodedata.normalize("NFC", part.strip())
        if word and GURMUKHI.match(word) and HAS_BASE.search(word):
            out.append(word)
    return out


def load_gz_titles(path: str) -> set[str]:
    words: set[str] = set()
    with gzip.open(path, "rt", encoding="utf-8", errors="ignore") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            words.update(tokens_from_title(line))
    return words


def load_hunspell(path: str) -> set[str]:
    words: set[str] = set()
    with open(path, "r", encoding="utf-8", errors="ignore") as handle:
        next(handle, None)  # word-count header
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            word = unicodedata.normalize("NFC", line.split("/")[0].strip())
            if word and GURMUKHI.match(word) and HAS_BASE.search(word):
                words.add(word)
    return words


def main() -> None:
    wiki = load_gz_titles(os.path.join(RAW, "pawiki-titles.gz"))
    wikt = load_gz_titles(os.path.join(RAW, "pawiktionary-titles.gz"))
    hunspell = load_hunspell(os.path.join(RAW, "pa_IN.dic"))
    merged = wiki | wikt | hunspell

    dictionary = hunspell | wikt

    def bucket(words: set[str]) -> dict[str, list[str]]:
        grouped: dict[str, list[str]] = defaultdict(list)
        for word in words:
            n = len(akshars(word))
            if MIN_LEN <= n <= MAX_LEN:
                grouped[str(n)].append(word)
        return {length: sorted(set(grouped[length])) for length in map(str, range(MIN_LEN, MAX_LEN + 1))}

    guesses = bucket(merged)
    answers = bucket(dictionary)
    bank: dict[str, dict[str, list[str]]] = {}
    histogram = {}
    for length in map(str, range(MIN_LEN, MAX_LEN + 1)):
        guess_list = guesses[length]
        answer_list = answers[length] or guess_list
        bank[length] = {"guesses": guess_list, "answers": answer_list}
        histogram[length] = {
            "guesses": len(guess_list),
            "answers": len(answer_list),
        }

    payload = (
        "/* Generated by scripts/build_wordlist.py from open-source corpora.\n"
        " * Wikipedia/Wiktionary titles: CC BY-SA 4.0\n"
        " * LibreOffice pa_IN Hunspell: MPL-2.0\n"
        " * See data/NOTICE.txt\n"
        " */\n"
        "window.WORD_BANK = "
        + json.dumps(bank, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )
    os.makedirs(os.path.dirname(OUT_JS), exist_ok=True)
    with open(OUT_JS, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(payload)

    meta = {
        "sources": {
            "pawiki_titles": len(wiki),
            "pawiktionary_titles": len(wikt),
            "libreoffice_hunspell": len(hunspell),
            "merged_unique": len(merged),
        },
        "playable_by_length": histogram,
        "playable_total": {
            "guesses": sum(item["guesses"] for item in histogram.values()),
            "answers": sum(item["answers"] for item in histogram.values()),
        },
        "licenses": [
            "CC BY-SA 4.0 (Punjabi Wikipedia and Punjabi Wiktionary titles)",
            "MPL-2.0 (LibreOffice pa_IN Hunspell dictionary)",
        ],
    }
    with open(OUT_META, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(meta, handle, ensure_ascii=False, indent=2)
        handle.write("\n")

    print(json.dumps(meta, ensure_ascii=True, indent=2))
    print("wrote", OUT_JS, "bytes", os.path.getsize(OUT_JS))


if __name__ == "__main__":
    main()
